//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableHtml.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamoes
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public float Percentage { get; set; }
        public System.DateTime FechadelPrestamo { get; set; }
    }
}
